IntegratedBreedingPlatform/Middleware

- src/test/java/org/generationcp/middleware/service/impl/dataset/DatasetTypeServiceImplTest.java
> IBP-2938 CreateTestForGetObservationlevels

- src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java
> IBP-2822 IBP-2930 Fix perf issue in count child samples

- src/main/java/org/generationcp/middleware/dao/dms/GeolocationPropertyDao.java
- src/main/java/org/generationcp/middleware/manager/StudyDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/StudyDataManager.java
- src/test/java/org/generationcp/middleware/dao/dms/GeolocationPropertyDaoTest.java
- src/test/java/org/generationcp/middleware/data/initializer/StudyTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/StudyDataManagerImplTest.java
> IBP-2635 export csv improvements

- CHANGELOG.md
- src/main/java/org/generationcp/middleware/pojos/workbench/ToolName.java
- src/main/java/org/generationcp/middleware/pojos/workbench/WorkbenchUser.java
- src/main/resources/liquibase/workbench_changelog/12_5_0.xml
After-merge improvements
https://github.com/IntegratedBreedingPlatform/Workbench/pull/286
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/810
https://github.com/IntegratedBreedingPlatform/BreedingManager/pull/314
https://github.com/IntegratedBreedingPlatform/Commons/pull/229
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/232
https://github.com/IntegratedBreedingPlatform/Middleware/pull/679
> IBP-2958 IBP-3016 roles permissions addendum

- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
> Changing HashMap for LinkedHashMap to preserve instances order

- src/main/resources/liquibase/crop_changelog/12_4_0.xml
- src/main/resources/liquibase/workbench_changelog/12_5_0.xml
After data managers feedback, breeder, technician ad admin will become program roles as well as readOnly
IBP-3040
> IBP-3032 IBP-3040 Modify changesets

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/manager/InventoryDataManagerImpl.java
- src/main/java/org/generationcp/middleware/pojos/ims/Lot.java
- src/main/java/org/generationcp/middleware/pojos/report/TransactionReportRow.java
- src/main/resources/liquibase/crop_changelog/13_1_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/test/java/org/generationcp/middleware/dao/ims/TransactionDAOTest.java
- src/test/java/org/generationcp/middleware/data/initializer/InventoryDetailsTestDataInitializer.java
> Ibp 3104 lot creation date

- src/main/resources/liquibase/crop_changelog/13_1_0.xml
> Adding is null to update

- src/main/resources/liquibase/crop_changelog/12_5_1.xml
- src/main/resources/liquibase/crop_changelog/13_2_0.xml
- src/main/resources/liquibase/crop_master.xml
> IBP-3011 DM Changes

- src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java
- src/test/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDaoTest.java
Add cast to unsigned for numericals in appendOutOfBoundsTraitsFilteringToQuery
> IBP-3153 add cast to unsigned for numericals

- src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/dao/ims/StockTransactionDAO.java
- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/pojos/ims/Lot.java
- src/main/java/org/generationcp/middleware/pojos/ims/Transaction.java
- src/main/java/org/generationcp/middleware/service/InventoryServiceImpl.java
- src/main/resources/liquibase/crop_changelog/13_2_0.xml
- src/test/java/org/generationcp/middleware/dao/GermplasmDAOTest.java
- src/test/java/org/generationcp/middleware/dao/ims/LotDAOTest.java
- src/test/java/org/generationcp/middleware/dao/ims/TransactionDAOTest.java
- src/test/java/org/generationcp/middleware/data/initializer/InventoryDetailsTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/GermplasmDataManagerIntegrationTest.java
- src/test/java/org/generationcp/middleware/manager/InventoryDataManagerImplTestIT.java
- src/test/java/org/generationcp/middleware/operation/builder/ListInventoryBuilderTest.java
- src/test/java/org/generationcp/middleware/service/InventoryServiceImplTest.java
> Ibp 2976 move stock

- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
- src/main/java/org/generationcp/middleware/domain/germplasm/GermplasmDTO.java
- src/main/java/org/generationcp/middleware/manager/GermplasmDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/GermplasmDataManager.java
> First commit

- src/main/java/org/generationcp/middleware/service/impl/study/generation/ExperimentDesignServiceImpl.java
- src/test/java/org/generationcp/middleware/service/impl/study/generation/ExperimentDesignServiceImplTest.java
> IBP-3220 Fix bean initialization error in SSA

- src/main/java/org/generationcp/middleware/domain/oms/TermId.java
- src/main/java/org/generationcp/middleware/operation/saver/WorkbookSaver.java
- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
- src/main/java/org/generationcp/middleware/service/api/DataImportService.java
> IBP-3145 expt design mapping

- src/main/java/org/generationcp/middleware/domain/dms/StandardVariable.java
- src/main/java/org/generationcp/middleware/operation/builder/StandardVariableBuilder.java
- src/main/java/org/generationcp/middleware/operation/transformer/etl/StandardVariableTransformer.java
- src/test/java/org/generationcp/middleware/operation/builder/StandardVariableBuilderTest.java
> IBP-3203 alias mapping

- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
- src/test/java/org/generationcp/middleware/service/DataImportServiceImplTest.java
> IBP-3292 unit tests for3145 and3203

- src/main/resources/liquibase/workbench_changelog/13_4_1.xml
> IBP-3297 Change the shipped OpenCPU dataset transformation presets.

- src/main/java/org/generationcp/middleware/service/api/BrapiView.java
- src/main/java/org/generationcp/middleware/service/api/phenotype/PhenotypeSearchDTO.java
> Move inner class to separate class

- src/main/java/org/generationcp/middleware/dao/dms/GeolocationPropertyDao.java
- src/main/java/org/generationcp/middleware/manager/StudyDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/StudyDataManager.java
- src/test/java/org/generationcp/middleware/dao/dms/GeolocationPropertyDaoTest.java
- src/test/java/org/generationcp/middleware/manager/StudyDataManagerImplTest.java
Remove StudyDataManager.getInstanceIdLocationIdMap.
Remove StudyDataManagerImpl.getInstanceIdLocationIdMap.
Remove GeolocationPropertyDaoTest.testGetInstanceIdLocationIdMap.
Remove StudyDataManagerImplTest.testGetInstanceIdLocationIdMap.
IBP-3048-UseStudyInstanceLocation
> IBP-3048 Apply code cleanup 

- src/main/java/org/generationcp/middleware/dao/AttributeDAO.java
- src/main/java/org/generationcp/middleware/domain/germplasm/AttributeDTO.java
- src/main/java/org/generationcp/middleware/manager/GermplasmDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/GermplasmDataManager.java
- src/test/java/org/generationcp/middleware/dao/AttributeDAOTest.java
> Ibp 3217 attributes brapi

- src/main/resources/liquibase/crop_changelog/14_1_0.xml
> Added onFail MARK_RAN to nahuels changeset with id=v14.1.0-1

- src/test/java/org/generationcp/middleware/service/impl/study/StudyServiceImplIntegrationTest.java
Use PersonId instead of Workbench UserId
> IBP-3262-SetStudyDataManagerAnnotation Fix Unit Test 

- src/main/java/org/generationcp/middleware/service/impl/study/StudyServiceImpl.java
> IBP-3471 Removed Java8 functions since it causes SSA issue

- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
- src/test/java/org/generationcp/middleware/data/initializer/WorkbookTestDataInitializer.java
- src/test/java/org/generationcp/middleware/service/DataImportServiceImplITTest.java
- src/test/java/org/generationcp/middleware/service/DataImportServiceImplTestIT.java
Remove additional checking for identifying if trial instance already exists 
Create unit test
> IBP-3379 Check For Existing Trial Instance on Import

- src/main/java/org/generationcp/middleware/dao/ListDataPropertyDAO.java
- src/main/java/org/generationcp/middleware/domain/gms/GermplasmListNewColumnsInfo.java
- src/main/java/org/generationcp/middleware/domain/gms/ListDataColumnValues.java
- src/test/java/org/generationcp/middleware/data/initializer/GermplasmListNewColumnsInfoTestDataInitializer.java
Add attribute addedColumnCurrentSort. 
If addedColumnCurrentSort is null return columnValuesMap keyset.
> IBP-3448 AddedAttributeSort 

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionsSearchDto.java
Hi @nahuel-soldevilla and @clarysabel 
In this PR I added the germplasmList filter into the query of view transaction.
Include:https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/16
Please, review
Regards, Diego
> IBP-3406 filter transactions by germplasm list

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/SearchCompositeDto.java
- src/main/java/org/generationcp/middleware/service/api/inventory/TransactionService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImpl.java
- src/main/resources/liquibase/workbench_changelog/14_3_0.xml
- src/main/resources/liquibase/workbench_master.xml
Hi @clarysabel and @nahuel-soldevilla
In this PR I added the logic to update the pending Transaction to Confirm.
Include:
IntegratedBreedingPlatform/InventoryManager#18
IntegratedBreedingPlatform/BMSAPI#305
Please Review
Regards, Diego
> IBP-3408 confirm pending transaction service

- src/main/java/org/generationcp/middleware/domain/inventory/manager/LotUpdateRequestDto.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/SearchCompositeDto.java
- src/main/java/org/generationcp/middleware/pojos/ims/TransactionStatus.java
- src/main/java/org/generationcp/middleware/pojos/ims/TransactionType.java
- src/main/java/org/generationcp/middleware/service/api/inventory/LotService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/LotServiceImpl.java
- src/main/resources/liquibase/workbench_changelog/14_3_0.xml
- src/main/resources/liquibase/workbench_master.xml
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/306
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/19
https://github.com/IntegratedBreedingPlatform/Middleware/pull/768
> IBP-3515 update lots

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/service/api/inventory/TransactionService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImpl.java
HI, @nahuel-soldevilla  I made this PR in name of @clarysabel .
She created a query to obtain the transaction involved available balance.
Include:
IntegratedBreedingPlatform/InventoryManager#20
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/309
Regards, Diego
> IBP-3407 Query to get transactions that affects the available balance

- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
- src/main/resources/liquibase/crop_changelog/14_2_0.xml
- src/main/resources/liquibase/crop_changelog/14_3_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/test/java/org/generationcp/middleware/dao/GermplasmDAOTest.java
- src/test/java/org/generationcp/middleware/dao/GermplasmListDAOTest.java
- src/test/java/org/generationcp/middleware/dao/oms/GermplasmSearchDAOTest.java
- src/test/java/org/generationcp/middleware/data/initializer/GermplasmTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/GermplasmDataManagerIntegrationTest.java
Add g.grplce = 0 in where clause of GermplasmDAO.getById
> IBP-3523 Add GRPLCE = 0 in Criteria

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/ExtendedLotDto.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionDto.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImpl.java
- src/main/resources/liquibase/workbench_changelog/14_3_0.xml
- src/test/java/org/generationcp/middleware/dao/ims/TransactionDAOTest.java
Hi @clarysabel and @nahuel-soldevilla.
In this PR I added the generation file and modified the query to obtain the transaction. I added the LocationName and LocationAbbr also added logic to set the Pedigree.
#Inlcuded:
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/23
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/313
Please, review
Regards, Diego
> IBP-3416 export transactions

- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/ExtendedLotDto.java
- src/main/java/org/generationcp/middleware/service/api/inventory/TransactionService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImpl.java
- src/main/java/org/generationcp/middleware/service/pedigree/PedigreeServiceImpl.java
> Fixing cross generation

- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/ExtendedLotDto.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/LotsSearchDto.java
> Retrieve pending deposits

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
Hi @nahuel-soldevilla and @clarysabel 
In this PR replace the lotScaleName alias by lotUnitName according to changes in the View of Inventory
Please review.
Regards, Diego
> IBP-3579 sorting units in transactions Query

- src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyInstance.java
Add hasGeoJSON and hasFieldLayout to StudyInstance
> IBP-3183 IBP-3218 brapi fieldmap - geojson/georeference editor

- src/main/java/org/generationcp/middleware/service/FieldbookServiceImpl.java
- src/test/java/org/generationcp/middleware/service/FieldbookServiceImplTest.java
> IBP-3645 Set location ldefault to false

- src/main/java/org/generationcp/middleware/manager/GermplasmListManagerImpl.java
- src/test/java/org/generationcp/middleware/manager/GermplasmListManagerImplTest.java
>  IBP-3090 FixedErrorOnEmptyCrossesList

- src/test/java/org/generationcp/middleware/data/initializer/UserTestDataInitializer.java
Added new method for ProgramMembersPanelTest
> IBP-3644 FilterRolesByWorkbenchProject

- src/main/java/org/generationcp/middleware/pojos/workbench/MethodType.java
Create enum MethodType, this will be used as replacement to constant string values for MethodTypes: Generative, Derivative and Maintenance
> IBP-3616 MethodType

- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/service/api/inventory/LotService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/LotServiceImpl.java
- src/main/resources/liquibase/workbench_changelog/14_4_1.xml
- src/main/resources/liquibase/workbench_master.xml
- src/test/java/org/generationcp/middleware/IntegrationTestBase.java
- src/test/java/org/generationcp/middleware/service/impl/inventory/LotServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImplIntegrationTest.java
- src/test/resources/testContext.xml
Include:
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/37
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/333
> Ibp 3667 close lots

- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionDto.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionsSearchDto.java
- src/test/java/org/generationcp/middleware/dao/ims/TransactionDAOTest.java
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/338
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/42
Please, Review
> IBP-3594 inventory manager technical backlog

- src/main/resources/liquibase/crop_changelog/14_4_0.xml
- src/main/resources/liquibase/crop_changelog/14_4_1.xml
- src/main/resources/liquibase/crop_master.xml
Add liquibase script for adding fk to project.parent_project_id
IBP-3441-FKProjectParentId
> IBP-3441 Add FK to project.parent_project_id

- src/main/java/org/generationcp/middleware/service/api/BrapiView.java
- src/main/java/org/generationcp/middleware/service/api/phenotype/PhenotypeSearchDTO.java
Include all fields from prior versions.
> IBP-3679 Include Prior Versions Properties

- src/main/resources/liquibase/crop_changelog/15_1_0.xml
- src/main/resources/liquibase/crop_master.xml
Alter key_prefix data type from varchar(50) to varchar(255) matching the datatype of listdata.desig
> IBP-3749-AlterKeyPrefixDataType

- pom.xml
- src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java
- src/test/java/org/generationcp/middleware/dao/dms/GeolocationDaoTest.java
- src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoIntegrationTest.java
- src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoTest.java
Excluding Null values to avoid null pointer exception when sorting and displaying the values
> IBP-3695-ExcludeNullValues

- src/main/java/org/generationcp/middleware/operation/saver/WorkbookSaver.java
- src/main/resources/liquibase/crop_changelog/15_1_0.xml
- src/test/java/org/generationcp/middleware/operation/saver/WorkbookSaverTest.java
> IBP-3730 remove unnecessary creation of stocks

- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
- src/main/java/org/generationcp/middleware/domain/inventory/util/LotTransformer.java
- src/main/java/org/generationcp/middleware/manager/InventoryDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/InventoryDataManager.java
- src/main/java/org/generationcp/middleware/operation/builder/ListInventoryBuilder.java
- src/test/java/org/generationcp/middleware/manager/InventoryDataManagerImplTestIT.java
Hi @nahuel-soldevilla and @clarysabel 
This PR is part of the remove the old Manage Inventory in Manage Germpalsm
Include:
https://github.com/IntegratedBreedingPlatform/BreedingManager/pull/341
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/865
https://github.com/IntegratedBreedingPlatform/Workbench/pull/341
Please, review
Regards, Diego
> IBP-3512 Remove old Manage Inventory code from Manage Germpalsm.

- src/main/resources/liquibase/crop_changelog/15_2_0.xml
- src/main/resources/liquibase/crop_master.xml
> Add ims_transaction lotid  FK to ims_lot table

- src/main/resources/liquibase/crop_changelog/15_3_0.xml
> IBP-3798 Corrected the name of indices.

- src/main/java/org/generationcp/middleware/dao/dms/ProjectPropertyDao.java
- src/main/java/org/generationcp/middleware/operation/builder/DataSetBuilder.java
- src/test/java/org/generationcp/middleware/dao/dms/ProjectPropertyDaoTest.java
- src/test/java/org/generationcp/middleware/operation/builder/DataSetBuilderTest.java
Remove previous fix
Add new condition for filtering variables, exclude variables with variable type Environment and Study Details 
Modify Unit test
> IBP-3402-DataSetColumns

- src/main/java/org/generationcp/middleware/manager/StudyDataManagerImpl.java
- src/test/java/org/generationcp/middleware/manager/StudyDataManagerImplTest.java
Check if projectproperty is a categorical variable if yes get the actual value
> IBP-3860-UseCategoricalValue

- src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
- src/main/java/org/generationcp/middleware/manager/PedigreeDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/PedigreeDataManager.java
- src/test/java/org/generationcp/middleware/dao/oms/GermplasmSearchDAOTest.java
Added function accept multiple gid
> IBP-3853-UsePedigreeDetailsForFGIDMGID

- src/main/java/org/generationcp/middleware/service/impl/study/StudyInstance.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyInstanceServiceImpl.java
Add experimentId in studyinstance (middleware) 
Set value of experimentId when creating instance
> IBP-3863-InstanceExperimentId

- src/main/java/org/generationcp/middleware/domain/fieldbook/FieldMapLabel.java
- src/test/java/org/generationcp/middleware/dao/dms/ExperimentPropertyDaoIntegrationTest.java
GetPlotCoordinate should return value as Range value Col value format.
> IBP-3904-RangeColFormat

- src/main/resources/liquibase/crop_changelog/15_4_0.xml
> IBP-3942 Fix the author and id name of the changeset.

- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
> IBP-3777 Adding recover Selection and Traits.

- src/main/java/org/generationcp/middleware/hibernate/DataSourceProperties.java
> IBP-3793 Retrieve property from system environment variables

- src/main/java/org/generationcp/middleware/dao/GermplasmStudySourceDAO.java
Fixing filters by contains text.
> IBP-3953 Designation filter is not working in Crosses and Selections

- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
> IBP-4034 Fix error in executing calculated variable.

- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/service/InventoryServiceImpl.java
- src/test/java/org/generationcp/middleware/service/InventoryServiceImplTest.java
Modify sql for searching existing id and regex to be case insensitive
> IBP-4030-GenerateStockIdCaseInsensitive

- src/main/java/org/generationcp/middleware/service/impl/study/StudyGermplasmServiceImpl.java
> IBP-4068 Add null checking for ENTRY_TYPE value

- src/main/java/org/generationcp/middleware/dao/LocationDAO.java
- src/main/java/org/generationcp/middleware/manager/LocationDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/LocationDataManager.java
- src/main/java/org/generationcp/middleware/service/api/inventory/LotService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/LotServiceImpl.java
- src/test/java/org/generationcp/middleware/service/impl/inventory/LotServiceImplIntegrationTest.java
Logic: If program is null, then only locations with no program assigned are retrieved. If program is not null, then locations with no program assigned plus locations assigned to the current program are retrieved.
IBP-4049
> Fix GET locations service and all places where it is used

- src/main/java/org/generationcp/middleware/service/api/study/StudyEntryDto.java
> Adding condition to verify values are not null before building Optional

- src/main/java/org/generationcp/middleware/domain/dms/Enumeration.java
Reverts IntegratedBreedingPlatform/Middleware#902
> Revert "IBP-4029 convert germplasm tab to angular table"

- src/main/java/org/generationcp/middleware/util/Util.java
> IBP-2753-ImportKSUDateFormat

- src/main/java/org/generationcp/middleware/domain/etl/Constants.java
- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
- src/main/java/org/generationcp/middleware/util/Util.java
- src/main/resources/mw_messages_en.properties
Created reusable logic for checking if measurement variable datatype and it's value is correct (numeric) 
Added logic for checking trial instance value in observation variables
> IBP-3528-ValidateTrialInstanceValue

- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListGeneratorDTO.java
- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListService.java
- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/GermplasmListDataDAO.java
- src/main/java/org/generationcp/middleware/domain/germplasm/GermplasmListTypeDTO.java
- src/main/java/org/generationcp/middleware/pojos/GermplasmList.java
- get germplasm list types
- save germplasm list 
- new enum for GermplasmList Status
No new permission created for now
> IBP-3944 save germplasm list

- src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java
- src/test/java/org/generationcp/middleware/service/impl/study/StudyServiceImplIntegrationTest.java
Modified method appendStudySummaryFromQuery to include deleted=0 in where caluse 
Method used in creating sql 
/{crop}/brapi/v1/trials - countStudies 
/{crop}/brapi/v1/trials - getStudies
/{crop}/brapi/v2/trials - countStudies
/{crop}/brapi/v2/trials - getStudies
> IBP-4122-AddIsDeletedToSQLFilter

- src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java
- src/main/java/org/generationcp/middleware/domain/oms/TermId.java
- src/main/java/org/generationcp/middleware/service/api/dataset/DatasetService.java
- src/main/java/org/generationcp/middleware/service/api/dataset/ObservationUnitRow.java
- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
Please review.
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/429
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/945
Regards, Diego
> IBP-4149 add stock id from plating preparation in observation tab

- src/main/java/org/generationcp/middleware/manager/LocationDataManagerImpl.java
- src/main/java/org/generationcp/middleware/service/FieldbookServiceImpl.java
- src/main/java/org/generationcp/middleware/service/Service.java
Please review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/948
https://github.com/IntegratedBreedingPlatform/Commons/pull/285
Regards, Diego
>  IBP-4039 Removing Deprecate fieldmap print labels.

- src/main/java/org/generationcp/middleware/service/impl/study/germplasm/source/GermplasmStudySourceServiceImpl.java
Please, review
Include:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/951
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/438
Regard, Diego
>  IBP-4061 Replace method by countGermplasmStudySourceList to count the germplasm

- src/main/java/org/generationcp/middleware/manager/StudyDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/StudyDataManager.java
- src/main/java/org/generationcp/middleware/service/api/study/StudyInstanceService.java
- src/main/java/org/generationcp/middleware/service/api/study/StudyService.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyInstanceServiceImpl.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyServiceImpl.java
- src/test/java/org/generationcp/middleware/service/impl/study/StudyInstanceServiceImplTest.java
Added checking of hasMeansDataset when setting canbedeleted attribute
> IBP-3233-SetCanBeDeletedFalseIfHasMeansDataset

- src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java
- src/main/java/org/generationcp/middleware/dao/dms/GeolocationPropertyDao.java
- src/main/java/org/generationcp/middleware/dao/dms/ProjectPropertyDao.java
Exclude deleted studies
Set additional props values to empty string if null
> IBP-3919 study resource brapi get studies v2

- src/main/java/org/generationcp/middleware/service/impl/study/StudyInstanceServiceImpl.java
> Ibp-3962 cannot remove values for site alt variable in enviroment details

- src/main/java/org/generationcp/middleware/dao/LocationDAO.java
- src/main/java/org/generationcp/middleware/manager/LocationDataManagerImpl.java
- src/main/java/org/generationcp/middleware/pojos/Location.java
- src/main/java/org/generationcp/middleware/pojos/dms/ProgramFavorite.java
- src/test/java/org/generationcp/middleware/dao/LocationDAOTest.java
- src/test/java/org/generationcp/middleware/data/initializer/LocationTestDataInitializer.java
- src/test/java/org/generationcp/middleware/data/initializer/StudyTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/LocationDataManagerImplTest.java
> renamed location.uniqueID by location.programUUID

- src/main/java/org/generationcp/middleware/operation/saver/StockSaver.java
- src/main/java/org/generationcp/middleware/pojos/dms/StockModel.java
- src/main/java/org/generationcp/middleware/pojos/dms/StockProperty.java
- src/main/java/org/generationcp/middleware/service/impl/study/generation/StockModelGenerator.java
- src/main/resources/liquibase/crop_changelog/17_1_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/test/java/org/generationcp/middleware/dao/dms/StockDaoIntegrationTest.java
- src/test/java/org/generationcp/middleware/dao/oms/CVTermRelationshipDaoTest.java
> IBP-4138 Removing rank column from stockprop table.

- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
Modify logic in addEntryTypeVariableIfNotExists, if Entry_Type exists do not create the variable, if not exists in observation add default value in observation.
cc @darla-leafnode
> IBP-4255-AddEntryTypeSucceedingImport

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/test/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImplIntegrationTest.java
> Fix issue with progenitors not being updated if breeding method is not specified

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
> IBP=4109 Fix Breeding Method Validation

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameService.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameServiceImpl.java
- src/main/java/org/generationcp/middleware/domain/germplasm/GermplasmNameRequestDto.java
- src/test/java/org/generationcp/middleware/api/germplasm/GermplasmNameServiceImplIntegrationTest.java
- src/test/resources/testContext.xml
> IBP-4434 implement names resource calls

- src/main/java/org/generationcp/middleware/domain/gms/SystemDefinedEntryType.java
- src/main/resources/liquibase/crop_changelog/17_4_0.xml
- src/main/resources/liquibase/crop_master.xml
New variable SystemDefinedEntryType.NON_REPLICATED_ENTRY
Liquibase script
> IBP-4476-PRepDesignNonReplicatedEntries

- src/main/java/org/generationcp/middleware/api/germplasm/search/GermplasmSearchRequest.java
- src/main/java/org/generationcp/middleware/api/germplasm/search/GermplasmSearchResponse.java
- src/main/java/org/generationcp/middleware/api/germplasm/search/GermplasmSearchService.java
- src/main/java/org/generationcp/middleware/api/germplasm/search/GermplasmSearchServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
- src/main/java/org/generationcp/middleware/dao/ProgramPresetDAO.java
- src/main/java/org/generationcp/middleware/domain/labelprinting/LabelPrintingType.java
- src/main/java/org/generationcp/middleware/pojos/workbench/PermissionsEnum.java
- src/main/resources/liquibase/crop_changelog/17_4_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/main/resources/liquibase/workbench_changelog/17_4_0.xml
- src/main/resources/liquibase/workbench_master.xml
- src/test/java/org/generationcp/middleware/dao/oms/GermplasmSearchDAOTest.java
> IBP-4205 Export data and labels from germplasm search

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
- src/main/java/org/generationcp/middleware/domain/germplasm/GermplasmDto.java
- src/test/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImplIntegrationTest.java
> IBP-4490 Germplasm Details Minor Improvements

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
> Extending children validation to all cases

- src/main/java/org/generationcp/middleware/dao/PermissionDAO.java
- src/main/java/org/generationcp/middleware/dao/ProjectDAO.java
- src/test/java/org/generationcp/middleware/dao/PermissionDAOTest.java
- src/test/java/org/generationcp/middleware/dao/ProjectDAOTest.java
> IBP-4438 IBP-4439 permission issues

- src/main/java/org/generationcp/middleware/dao/LocationDAO.java
> According to geojson, longitude goes before than latitude

- src/main/java/org/generationcp/middleware/manager/PedigreeDataManagerImpl.java
- src/test/java/org/generationcp/middleware/data/initializer/GermplasmPedigreeTreeTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/PedigreeDataManagerImplTest.java
Unit test for unknown male parent and known female parent 
If unknown parent, create node with the known female parent child
> IBP-4395-NodeForUnknownMaleKnownFemale

- src/main/java/org/generationcp/middleware/dao/GermplasmStudySourceDAO.java
- src/main/java/org/generationcp/middleware/domain/germplasm/GermplasmOriginDto.java
In order to apply IBP-4527 to germplasmOrigin study link
> IBP-4582 add programUUID to germplasmOrigin

- src/main/java/org/generationcp/middleware/pojos/workbench/PermissionsEnum.java
> IBP-4572 verify correct imlementation of crop management permission

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
> IBP-4623 Fix Import Germplasm Update

- src/main/java/org/generationcp/middleware/manager/GermplasmDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/PedigreeDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/GermplasmDataManager.java
- src/main/java/org/generationcp/middleware/manager/api/PedigreeDataManager.java
- src/test/java/org/generationcp/middleware/manager/GermplasmDataManagerIntegrationTest.java
- src/test/java/org/generationcp/middleware/manager/PedigreeDataManagerTest.java
Remove unused methods 
Remove unit test for unused methods
> IBP-4457-CodeCleanup

- src/main/java/org/generationcp/middleware/dao/UserInfoDAO.java
- src/main/java/org/generationcp/middleware/pojos/workbench/UserInfo.java
- src/main/java/org/generationcp/middleware/service/impl/user/UserServiceImpl.java
- Remove UserInfoDAO.updateLoginCounter
- Create userInfo if not exist (edge case)
Related to https://github.com/IntegratedBreedingPlatform/Workbench/pull/503#discussion_r651765158
> IBP-4610: Move incrementUserInfoLogInCount logic to userService

- src/main/java/org/generationcp/middleware/manager/StudyDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/StudyDataManager.java
- src/test/java/org/generationcp/middleware/dao/GermplasmDAOTest.java
- src/test/java/org/generationcp/middleware/dao/GermplasmListDAOTest.java
- src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoIntegrationTest.java
- src/test/java/org/generationcp/middleware/dao/dms/PhenotypeSaverTest.java
- src/test/java/org/generationcp/middleware/dao/dms/StudySearchDaoTest.java
- src/test/java/org/generationcp/middleware/data/initializer/StudyTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/StudyDataManagerImplTest.java
- src/test/java/org/generationcp/middleware/operation/saver/ProjectPropertySaverTest.java
- src/test/java/org/generationcp/middleware/service/FieldbookServiceTest.java
- src/test/java/org/generationcp/middleware/service/impl/study/StudyInstanceServiceImplTest.java
- src/test/java/org/generationcp/middleware/service/impl/study/generation/ExperimentDesignServiceImplTest.java
> Removed StudyDataManager functions that were only used in tests

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/main/resources/mw_messages_en.properties
- src/test/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImplIntegrationTest.java
> IBP-4721 Allow germplasm update even when germplasm has progeny.

- src/main/resources/liquibase/crop_changelog/14_1_0.xml
- src/main/resources/liquibase/crop_changelog/18_3_0.xml
- src/main/resources/liquibase/crop_master.xml
Added changeset for drop unused table ims_stock_transaction_bkp
> IBP-4285-DropBackupTables

- src/main/java/org/generationcp/middleware/dao/oms/VariableOverridesDao.java
- src/main/java/org/generationcp/middleware/domain/ontology/VariableOverridesDto.java
- src/main/java/org/generationcp/middleware/manager/ontology/OntologyVariableDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/ontology/api/OntologyVariableDataManager.java
> IBP-4744 enforce variable name and alias uniqueness within a crop

- src/main/java/org/generationcp/middleware/operation/saver/ExperimentPropertySaver.java
- src/main/java/org/generationcp/middleware/pojos/dms/ExperimentProperty.java
> Replace usage of INSERT INTO by hibernate in fieldmap

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameServiceImpl.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmService.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeDTO.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeRequestDTO.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeService.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/UserDefinedFieldDAO.java
- src/main/java/org/generationcp/middleware/manager/ManagerFactory.java
- src/test/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImplTest.java
- src/test/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeServiceImplIntegrationTest.java
- src/test/resources/testContext.xml
Include: 
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/545
https://github.com/IntegratedBreedingPlatform/Workbench/pull/514
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1016
> IBP-4607 Get all name types and Create a new one.

- src/main/java/org/generationcp/middleware/dao/PermissionDAO.java
- src/main/java/org/generationcp/middleware/dao/UserRoleDao.java
Merge "Add Program" fixes to main hotfix branch IBP-4816
> IBP-4800 hotfix add program

- src/main/java/org/generationcp/middleware/pojos/dms/Geolocation.java
> IBP-4819 Fix error in deleting study instance

- src/main/java/org/generationcp/middleware/api/program/ProgramService.java
- src/main/java/org/generationcp/middleware/api/program/ProgramServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/RoleDAO.java
- src/main/java/org/generationcp/middleware/dao/WorkbenchUserDAO.java
- src/main/java/org/generationcp/middleware/domain/workbench/AddProgramMemberRequestDto.java
- src/main/java/org/generationcp/middleware/service/api/user/UserService.java
- src/main/java/org/generationcp/middleware/service/impl/user/UserServiceImpl.java
> Impementing services to add and remove users from a program

- src/main/java/org/generationcp/middleware/dao/PermissionDAO.java
- src/main/java/org/generationcp/middleware/dao/UserRoleDao.java
Some commits were done directly in the hotfix, this is to push them into master
cc @darla-leafnode @mderamos
> IBP-4800 update master with hotfix commits

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameService.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameServiceImpl.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeRequestDTO.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeService.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/ListDataPropertyDAO.java
- src/main/java/org/generationcp/middleware/dao/NameDAO.java
- src/main/resources/liquibase/workbench_changelog/18_4_0.xml
- src/main/resources/liquibase/workbench_master.xml
- src/test/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeServiceImplIntegrationTest.java
Please Review.
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/519
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/556
> IBP-4794 Manager Metadata (Name Types)

- src/main/java/org/generationcp/middleware/api/brapi/v1/image/ImageNewRequest.java
- src/main/java/org/generationcp/middleware/api/file/FileMetadataDTO.java
- src/main/java/org/generationcp/middleware/api/file/FileMetadataFilterRequest.java
- src/main/java/org/generationcp/middleware/api/file/FileMetadataMapper.java
- src/main/java/org/generationcp/middleware/api/file/FileMetadataService.java
- src/main/java/org/generationcp/middleware/api/file/FileMetadataServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/FileMetadataDAO.java
- src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java
- src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java
- src/main/java/org/generationcp/middleware/dao/oms/CVTermDao.java
- src/main/java/org/generationcp/middleware/domain/ontology/DataType.java
- src/main/java/org/generationcp/middleware/hibernate/listener/CustomPreDeleteEventListener.java
- src/main/java/org/generationcp/middleware/manager/ontology/OntologyVariableDataManagerImpl.java
- src/main/java/org/generationcp/middleware/pojos/file/FileMetadata.java
- src/main/java/org/generationcp/middleware/service/api/dataset/ObservationUnitRow.java
- src/main/resources/liquibase/crop_changelog/18_4_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/main/resources/mw_messages_en.properties
- file deletion
- file upload refactor and improvements
- link only obs unit (fk to phenoype was added and removed in a later commit)
- link file metadata to cvterm
- Adapt audit CustomPreDeleteEventListener to use pk column name  bec74199caf8f25e2b5318255f81b91ec9acb1fb
- new (partially implemented) method: CVTermDao.getVariablesWithFilter (IBP-4705) 959ceddaa101091ba7eefcc01af8c740ff672a1b
> IBP-4815 file upload improvements

- src/main/resources/liquibase/workbench_changelog/18_4_1.xml
- src/main/resources/liquibase/workbench_changelog/19_1_0.xml
- src/main/resources/liquibase/workbench_master.xml
Please revew.
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/532
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/570
> IBP-4908 cannot use email grather than 40 characters

- src/main/resources/liquibase/crop_changelog/18_3_0.xml
- src/main/resources/liquibase/crop_changelog/18_4_1.xml
- src/main/resources/liquibase/crop_master.xml
Creating PR on @mchabito behalf
> V19 DM changes - fixes for IBP-4665 and IBP-4885

- src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
> IBP-4682 Use IN instead of exists

- src/main/java/org/generationcp/middleware/manager/StudyDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/StudyDataManager.java
Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/320
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1025
> IBP-4822 browse study error when enviroments have the same location name

- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeService.java
- src/main/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeServiceImpl.java
- src/main/java/org/generationcp/middleware/api/nametype/NameTypeMetadataFilterRequest.java
- src/main/java/org/generationcp/middleware/dao/UserDefinedFieldDAO.java
- src/test/java/org/generationcp/middleware/api/nametype/GermplasmNameTypeServiceImplIntegrationTest.java
Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/540
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/577
> IBP-4918 implement name types filter

- src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java
- src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoIntegrationTest.java
> IBP-5169 Modified pagination

- src/main/java/org/generationcp/middleware/api/brapi/v2/germplasm/GermplasmImportRequest.java
> Fix Duplicate PUI validation

- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmAttributeService.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmAttributeServiceImpl.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameService.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmNameServiceImpl.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmService.java
- src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java
- src/main/java/org/generationcp/middleware/api/location/LocationDTO.java
- src/main/java/org/generationcp/middleware/api/location/LocationRequestDto.java
- src/main/java/org/generationcp/middleware/api/location/LocationService.java
- src/main/java/org/generationcp/middleware/api/location/LocationServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/AttributeDAO.java
- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
- src/main/java/org/generationcp/middleware/dao/NameDAO.java
- src/main/java/org/generationcp/middleware/domain/dms/LocationDto.java
- src/main/java/org/generationcp/middleware/service/api/inventory/LotService.java
- src/main/java/org/generationcp/middleware/service/api/study/StudyService.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/LotServiceImpl.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyServiceImpl.java
- src/test/java/org/generationcp/middleware/api/location/LocationServiceImplIntegrationTest.java
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/614
> IBP-5047 implement post patch delete locations

- src/main/java/org/generationcp/middleware/dao/oms/CVTermDao.java
- src/main/java/org/generationcp/middleware/domain/ontology/Variable.java
- src/main/java/org/generationcp/middleware/manager/ontology/OntologyScaleDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/ontology/OntologyVariableDataManagerImpl.java
- src/main/java/org/generationcp/middleware/operation/saver/CvTermSaver.java
- src/main/java/org/generationcp/middleware/operation/saver/StandardVariableSaver.java
- src/main/java/org/generationcp/middleware/pojos/oms/CVTerm.java
- src/main/resources/liquibase/crop_changelog/19_4_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/test/java/org/generationcp/middleware/dao/AttributeDAOTest.java
- src/test/java/org/generationcp/middleware/dao/CvTermDaoTest.java
- src/test/java/org/generationcp/middleware/dao/FileMetadataDAOTest.java
- src/test/java/org/generationcp/middleware/dao/GermplasmDAOTest.java
- src/test/java/org/generationcp/middleware/dao/audit/germplasm/GermplasmAuditDAOTest.java
- src/test/java/org/generationcp/middleware/data/initializer/CVTermTestDataInitializer.java
- src/test/java/org/generationcp/middleware/manager/GermplasmDataManagerIntegrationTest.java
- src/test/java/org/generationcp/middleware/manager/ontology/TestDataHelper.java
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/624
https://github.com/IntegratedBreedingPlatform/Workbench/pull/591
> IBP-4793 can not edit or delete system variables

- src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
Transform attribute pre-filter "where" sub-query into an inner join with sub-table, to be able to use LIMIT inside it.
> IBP-5041: Fix Performance issue in Germplasm search by attributes

- src/main/java/org/generationcp/middleware/dao/dms/ExperimentPropertyDao.java
validate param in getPlotObservationLevelRelationshipsByGeolocations
Fixes sql error, enables later validation of studyDbIds
> IBP-5002 IBP-4967 IBP-5002 Fix brapi/v2/observationunits issues

- src/main/resources/liquibase/workbench_changelog/19_4_1.xml
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/614
> IBP-2866 About page

- src/main/java/org/generationcp/middleware/pojos/workbench/PermissionsEnum.java
- src/main/resources/liquibase/workbench_changelog/19_5_0.xml
- src/main/resources/liquibase/workbench_master.xml
Plese, review
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/653
https://github.com/IntegratedBreedingPlatform/Workbench/pull/642
> IBP-5357 Lock/Unlock and delete permissions in Germplasm Lists.

- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListService.java
- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceImpl.java
- src/test/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceIntegrationTest.java
Making lists locked when moved to a crop list folder
IBP-5285
> Fixing inconsistencies when creating and cloning lists

- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceImpl.java
> set Max entry no to 0 instead of 1 when list is empty

- src/main/resources/liquibase/crop_changelog/19_5_0.xml
- src/main/resources/liquibase/crop_changelog/19_5_1.xml
- src/main/resources/liquibase/crop_master.xml
For review and merge please, @clarysabel . Thanks!
> IBP-5424 set historical list folders to have lhierarchy=null

- src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java
- remove BrAPI XY retrieval from COL/ROW fields from row col design
- remove setting of default value for x and y coordinates 
* both changes are applicable for v1, this is aligned with v2's current behavior
> IBP-5090: Change in BRAPI X and Y coordinates mapping

- src/main/java/org/generationcp/middleware/domain/inventory/common/SearchOriginCompositeDto.java
- src/main/java/org/generationcp/middleware/domain/inventory/manager/LotDepositRequestDto.java
- src/main/java/org/generationcp/middleware/service/api/dataset/ObservationUnitsSearchDTO.java
- src/main/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImpl.java
- src/test/java/org/generationcp/middleware/service/impl/inventory/TransactionServiceImplIntegrationTest.java
- src/test/resources/testContext.xml
Please, Review
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/660
https://github.com/IntegratedBreedingPlatform/Workbench/pull/656
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1063
> IBP-5394 create lots from planted observation units

- src/main/java/org/generationcp/middleware/api/location/LocationServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/LocationDAO.java
- src/main/java/org/generationcp/middleware/dao/LocdesDAO.java
- src/main/java/org/generationcp/middleware/dao/dms/GeolocationDao.java
Minor fixies.
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/668
https://github.com/IntegratedBreedingPlatform/Workbench/pull/665
> IBP-4838 manage program settings beta

- src/main/java/org/generationcp/middleware/api/location/LocationServiceImpl.java
> IBP-4838 Remove deleteGeolocations query from delete location process.

- src/main/java/org/generationcp/middleware/api/germplasm/search/GermplasmSearchRequest.java
- src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
- src/test/java/org/generationcp/middleware/dao/GermplasmSearchDAOTest.java
> IBP-5448 Implementation of germplasm external references filter

- src/main/resources/liquibase/crop_changelog/20_2_0.xml
- src/main/resources/liquibase/crop_master.xml
> IBP-5456 Remove program_uuid_bkp column from location and methods tables.

- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListService.java
- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDataViewDAO.java
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/692
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/691
> IBP-5590-Limit-add-column-in-germplasm-list

- src/main/java/org/generationcp/middleware/api/feedback/FeedbackDto.java
- src/main/java/org/generationcp/middleware/pojos/workbench/feedback/Feedback.java
- src/main/java/org/generationcp/middleware/pojos/workbench/feedback/FeedbackFeature.java
- src/main/java/org/generationcp/middleware/service/api/feedback/FeedbackService.java
- src/main/java/org/generationcp/middleware/service/impl/feedback/FeedbackServiceImpl.java
- src/main/resources/liquibase/workbench_changelog/20_4_1.xml
- src/test/java/org/generationcp/middleware/service/impl/feedback/FeedbackServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/feedback/FeedbackServiceImplTest.java
- src/test/resources/test.properties
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/693
https://github.com/IntegratedBreedingPlatform/BMSConfig/pull/114
https://github.com/IntegratedBreedingPlatform/Commons/pull/344
https://github.com/IntegratedBreedingPlatform/Workbench/pull/695
> IBP-5636-Implement_in-app_feedback_in_manage_program_settings

- src/main/java/org/generationcp/middleware/api/brapi/GermplasmListServiceBrapiImpl.java
> IBP-5593 - IBP-5593-improvements-to-post-lists

- src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java
- src/main/java/org/generationcp/middleware/dao/ims/SearchLotDaoQuery.java
> IBP-5442-get_lot_details_not_returning_location_abbr

- src/main/java/org/generationcp/middleware/dao/oms/CVTermDao.java
> Add empty string checking for variable name

- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListService.java
- src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceImpl.java
- src/test/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceIntegrationTest.java
> IBP-5441 - IBP-5441-Moving-to-crop-list-fix-locked-status

- src/main/java/org/generationcp/middleware/service/impl/inventory/PlantingServiceImpl.java
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1080
> IBP-5551 - IBP-5551-prepare_planting_inventory

- src/main/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDAO.java
- src/main/java/org/generationcp/middleware/manager/GermplasmDataManagerUtil.java
- src/test/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDAOTest.java
- src/test/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDataDAOTest.java
> Removed unused functions in Middleware

- src/main/java/org/generationcp/middleware/api/program/ProgramService.java
- src/main/java/org/generationcp/middleware/api/program/ProgramServiceImpl.java
- src/main/java/org/generationcp/middleware/manager/WorkbenchDataManagerImpl.java
- src/main/java/org/generationcp/middleware/manager/api/WorkbenchDataManager.java
- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
- src/test/java/org/generationcp/middleware/DataSetupTest.java
- src/test/java/org/generationcp/middleware/PerfDataSetupTest.java
- src/test/java/org/generationcp/middleware/WorkbenchTestDataUtil.java
- src/test/java/org/generationcp/middleware/brapi/ObservationServiceBrapiImplTest.java
- src/test/java/org/generationcp/middleware/brapi/TrialServiceBrapiImplTest.java
- src/test/java/org/generationcp/middleware/dao/CropTypeDAOTest.java
- src/test/java/org/generationcp/middleware/dao/PermissionDAOTest.java
- src/test/java/org/generationcp/middleware/dao/ProjectDAOTest.java
- src/test/java/org/generationcp/middleware/manager/StudyDataManagerImplTest.java
- src/test/java/org/generationcp/middleware/manager/WorkbenchDataManagerImplTest.java
- src/test/java/org/generationcp/middleware/service/FieldbookServiceTest.java
- src/test/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImplTest.java
- src/test/java/org/generationcp/middleware/service/impl/observationunit/ObservationUnitServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/study/StudyServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/user/UserServiceImplTest.java
> IBP-5699 - IBP-5699-WorkbenchDataManager-Cleaning

- src/main/java/org/generationcp/middleware/domain/etl/Constants.java
- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1096
> IBP-5739-Dataset_importer_add_entry_type_as_default

- src/main/java/org/generationcp/middleware/domain/etl/Constants.java
- src/main/java/org/generationcp/middleware/service/DataImportServiceImpl.java
- src/main/java/org/generationcp/middleware/service/api/DataImportService.java
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1097
> IBP-5805 import dataset issues

- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
> IBP-5849-germplasm-attributes-and-passports-are-not-included-in-the-exported-study-book

- src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java
Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/356
> IBP-5845-ENTRY_NO_and_ENTRY_TYPE_are_no_longer_available_in_MEANS_DATASET

- src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java
> IBP-5866-ExcludeCancelledTransactions

- src/main/java/org/generationcp/middleware/domain/oms/Term.java
- src/main/java/org/generationcp/middleware/domain/ontology/Term.java
- src/main/resources/liquibase/crop_changelog/21_5_0.xml
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/744
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/743
> IBP-5835-ontology_method_for_sta_brapp

- src/main/java/org/generationcp/middleware/util/PedigreeUtil.java
…e immediate source for a first derivation
IBP-5757
> IBP-5757-Fix-Pedigree-Edition-For-First-Derivation

- src/main/resources/liquibase/crop_changelog/21_3_0.xml
> IBP-5864-Fix_Entry_details_changeset

- src/main/java/org/generationcp/middleware/api/brapi/ObservationServiceBrapiImpl.java
- src/main/java/org/generationcp/middleware/api/brapi/VariableServiceBrapiImpl.java
- src/main/java/org/generationcp/middleware/api/brapi/VariableTypeGroup.java
- src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java
- src/main/java/org/generationcp/middleware/dao/dms/ProjectPropertyDao.java
- src/main/java/org/generationcp/middleware/dao/oms/CVTermDao.java
- src/main/java/org/generationcp/middleware/service/api/study/VariableDTO.java
- src/main/java/org/generationcp/middleware/service/impl/study/PhenotypeQuery.java
- src/test/java/org/generationcp/middleware/brapi/ObservationServiceBrapiImplTest.java
…AIT variables to the study (Plot dataset's projectprop) if they are not yet present.
> IBP-5824-Automatic Association Of Variables

- src/main/java/org/generationcp/middleware/dao/NameDAO.java
- src/main/java/org/generationcp/middleware/dao/UserDefinedFieldDAO.java
- src/test/java/org/generationcp/middleware/dao/UserDefinedFieldDAOTest.java
> IBP-5721-brapi-sync-deleted-names-nstat-9-are-being-retrieved-as-synonyms

- src/main/java/org/generationcp/middleware/api/brapi/v2/observationlevel/ObservationLevelEnum.java
- src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationLevelMapper.java
- src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationUnitServiceImpl.java
- src/main/java/org/generationcp/middleware/dao/dms/DatasetTypeDAO.java
- src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java
- src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/dataset/DatasetTypeServiceImplTest.java
…etrieving the observationLevels and searching/getting observation units.
> IBP-5681- Observation Level Names Consistency

- src/main/java/org/generationcp/middleware/api/germplasm/pedigree/GermplasmPedigreeServiceImpl.java
- src/main/java/org/generationcp/middleware/pojos/Name.java
> IBP-5881 fix cop and pedigree performance

- src/main/resources/liquibase/crop_changelog/21_5_0.xml
> IBP-5880-inventory_lots_variables

- src/main/java/org/generationcp/middleware/operation/builder/ListInventoryBuilder.java
- src/test/java/org/generationcp/middleware/service/impl/inventory/LotServiceImplIntegrationTest.java
> IBP-3768-Inventory-Cleanup

- src/main/java/org/generationcp/middleware/service/FieldbookServiceImpl.java
- src/main/java/org/generationcp/middleware/service/api/GermplasmGroupingService.java
- src/main/java/org/generationcp/middleware/service/impl/GermplasmGroupingServiceImpl.java
- src/test/java/org/generationcp/middleware/service/impl/GermplasmGroupingServiceImplTest.java
> IBP-5912-improve-advancing-lines-when-there-are-several-grouped-germplasms-present-in-the-advance-list-entries

- src/main/resources/liquibase/crop_changelog/22_1_0.xml
> IBP-5944-drop-tables-atributs-invalid-atype-bkp-and-udflds-attributes-bkp

- src/main/java/org/generationcp/middleware/dao/dms/StockDao.java
> IBP-5943-cannot_add_new_entries_in_germplasm_and_checks

- src/main/resources/liquibase/crop_changelog/22_1_0.xml
> Fix update query

- src/main/java/org/generationcp/middleware/pojos/workbench/PermissionsEnum.java
> IBP-3989 Hide restricted actions

- src/main/resources/liquibase/crop_changelog/22_3_0.xml
- src/main/resources/liquibase/crop_master.xml
Schema-changes
listdata.entrycd_bkp
stock.type_id_bkp
stock.value_bkp
Make program_location_default.breeding_location_id not null
IBP-5896 IBP-5897 IBP-5949
> IBP-5896-IBP-5897-IBP-5949-Schema-changes

- src/main/java/org/generationcp/middleware/dao/WorkbenchUserDAO.java
- src/main/java/org/generationcp/middleware/service/api/user/UserService.java
- src/main/java/org/generationcp/middleware/service/impl/user/UserServiceImpl.java
> IBP-5978-RestrictNumberOfActiveUsers

- src/main/java/org/generationcp/middleware/api/brapi/TrialServiceBrapiImpl.java
- src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationUnitServiceImpl.java
- src/main/java/org/generationcp/middleware/operation/builder/ExperimentBuilder.java
- src/main/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImpl.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyEntryServiceImpl.java
- src/main/java/org/generationcp/middleware/service/impl/study/StudyServiceImpl.java
- src/main/resources/liquibase/crop_changelog/22_3_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/test/java/org/generationcp/middleware/service/impl/study/StudyServiceImplTest.java
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1132
https://github.com/IntegratedBreedingPlatform/Commons/pull/367
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/770
> IBP-4059 recategorize obs unit id as experimental design variable

- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
Some performance issues were detected on large databases.
relates to: https://github.com/IntegratedBreedingPlatform/Middleware/pull/1370/files#r1017941844
> IBP-5981 Bring back pagination on pedigree search

- src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
This reverts commit 5214bdf37aae3b508a0d86e7b379d41b69c4700b.
> IBP-5777 IBP-5981 Revert Addition Of Pagination In Pedigree Search

- src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationUnitServiceImpl.java
> IBP-6058_duplicate_OBS_UNI_ID_executing_post_v2_observationunits 

- src/main/java/org/generationcp/middleware/dao/WorkbenchUserDAO.java
- src/main/java/org/generationcp/middleware/pojos/Person.java
- src/main/java/org/generationcp/middleware/pojos/workbench/WorkbenchUser.java
- src/main/java/org/generationcp/middleware/service/api/user/UserService.java
- src/main/java/org/generationcp/middleware/service/impl/user/UserServiceImpl.java
- src/test/java/org/generationcp/middleware/DataSetupTest.java
- src/test/java/org/generationcp/middleware/PerfDataSetupTest.java
- src/test/java/org/generationcp/middleware/WorkbenchTestDataUtil.java
- src/test/java/org/generationcp/middleware/brapi/ObservationServiceBrapiImplTest.java
- src/test/java/org/generationcp/middleware/brapi/TrialServiceBrapiImplTest.java
- src/test/java/org/generationcp/middleware/dao/CropTypeDAOTest.java
- src/test/java/org/generationcp/middleware/dao/PermissionDAOTest.java
- src/test/java/org/generationcp/middleware/dao/ProjectDAOTest.java
- src/test/java/org/generationcp/middleware/dao/SampleListDaoTest.java
- src/test/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDAOTest.java
- src/test/java/org/generationcp/middleware/manager/RoleServiceImplTest.java
- src/test/java/org/generationcp/middleware/manager/StudyDataManagerImplTest.java
- src/test/java/org/generationcp/middleware/operation/saver/ProjectPropertySaverTest.java
- src/test/java/org/generationcp/middleware/service/FieldbookServiceTest.java
- src/test/java/org/generationcp/middleware/service/MethodServiceImplTest.java
- src/test/java/org/generationcp/middleware/service/impl/dataset/DatasetServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/observationunit/ObservationUnitServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/security/UserDeviceMetaDataServiceImplTest.java
- src/test/java/org/generationcp/middleware/service/impl/study/StudyServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/service/impl/user/UserServiceImplTest.java
- src/test/java/org/generationcp/middleware/utils/test/IntegrationTestDataInitializer.java
> IBP-6074-Delete-addUser

- src/main/resources/liquibase/crop_changelog/22_4_0.xml
- src/main/resources/liquibase/crop_master.xml
- src/test/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImplIntegrationTest.java
- src/test/java/org/generationcp/middleware/audit/NameAuditIntegrationTest.java
- src/test/java/org/generationcp/middleware/manager/GermplasmDataManagerIntegrationTest.java
> IBP-4663-AddNamesToNameTypeFK

- src/main/java/org/generationcp/middleware/api/cropparameter/CropParameterDTO.java
- src/main/java/org/generationcp/middleware/dao/CropParameterDAO.java
- clear text value should not be saved on db
> IBP-6071: fix bug found on update of encrypted value

- src/main/java/org/generationcp/middleware/api/location/search/LocationSearchRequest.java
- src/main/java/org/generationcp/middleware/dao/location/LocationSearchDAOQuery.java
- separate location search request DTO for brapi v2
> IBP-6283: fix filter of location on crop settings manager

- src/main/java/org/generationcp/middleware/operation/parser/WorkbookParser.java
> IBP-6175-incorrect_header_when_imported_study_book

- src/main/java/org/generationcp/middleware/service/impl/inventory/PlantingServiceImpl.java
When searching for observations to be processed, ensure that entry details variables are included in the visible columns so that the values for these variables will be returned.
> IBP-6333 Fix Planting Inventory Withdrawal By EntryDetail

- src/main/java/org/generationcp/middleware/service/impl/study/PhenotypeQuery.java
> IBP-6148-IncludeSelectionVariableInObsUnitSearch

- src/main/resources/liquibase/crop_changelog/18_4_0.xml
- src/main/resources/liquibase/workbench_changelog/12_5_0.xml
> IBP-6352-fix-changeset-with-column-as-null

- src/main/java/org/generationcp/middleware/domain/ontology/Variable.java
- src/main/java/org/generationcp/middleware/manager/ontology/OntologyVariableDataManagerImpl.java
> IBP-5758-IncludeLotsCountInVariableMetadata

- src/main/resources/liquibase/workbench_changelog/24_4_0.xml
- src/main/resources/liquibase/workbench_master.xml
> IBP-6396-update_open_cpu_endpoint
