src/main/java/org/generationcp/middleware/operation/parser/WorkbookParser.java
I'm not sure why the extra `col++` was there in https://github.com/IntegratedBreedingPlatform/Workbench/commit/cb35c7de98bb609f73755a9889d61360b39bc0ca#diff-4e08472cc8c6b075252ffd97a0b97eaeR288, maybe it was a while loop at some point?
In other (similar) legacy code is not there: https://github.com/menghuinantang/Fieldbook/blob/cc26ea7c8629265ac51be79ca1eb4d0d96f2d83f/src/main/java/com/efficio/fieldbook/web/nursery/service/impl/ImportGermplasmFileServiceImpl.java#L611
=> IBP-3247 IBP-3244 fix workbook parse infinite loop

src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java, src/main/java/org/generationcp/middleware/service/api/inventory/LotService.java, src/main/java/org/generationcp/middleware/service/impl/inventory/LotServiceImpl.java
- Previous approach won't scale for a large list of gids
- Instead of sending list of gids as parameter, take advantage of lot
query and lotSearch filters.
- Middleware: Wrap lot search query and join atributs by gid
in a new query
New approach can export ~ 100.000 rows in ~ 20s
For excel export this will result in an error because it can only handle
65535 rows.
=> IBP-3706 IBP-3665 Fix performance of lot label printing

src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java
Remove trnqty column from the query because the method only needs to return the stockId values.
IBP-3715
=> IBP-3715 Fix Error in Bulking Reciprocals and Duplicates

src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java, src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotDepositRequestDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotUpdateRequestDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotWithdrawalInputDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotsSearchDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionsSearchDto.java, src/main/java/org/generationcp/middleware/service/api/inventory/LotService.java, src/main/java/org/generationcp/middleware/service/impl/inventory/LotServiceImpl.java
- Adding Filter query by LotUUID in TransactionDAO.
- Adding Filter query by LotUUID in LotDAO.
- Replacing the using lotId and use the lotUUID instead.
Includes:
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/49
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/348
Please, Review
=> IBP-3760 enable the use lot UUID to external clients

src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java, src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoIntegrationTest.java
Remove checking if cvtermprop.value is empty condition 
Use cvterm_id as observationVariableId 
Modify Existing unit test: add cvtermprop value
=> IBP-3802-SetObservationVariableId

src/main/java/org/generationcp/middleware/dao/dms/ProjectPropertyDao.java, src/main/java/org/generationcp/middleware/domain/oms/TermId.java, src/test/java/org/generationcp/middleware/dao/dms/ProjectPropertyDaoTest.java
Modify script when retrieving property name and value when using the api
/{crop}​/brapi​/v1​/studies​/{studyDbId}
/{crop}/brapi/v2/studies/{studyDbId}
When creating study, the cvterm_id of the selected possible value of categorical variable is being saved as value projectproperty table, to retrieve the actual value (definition), added a join for the cvterm_relationship
Added unit test for categorical variable
=> IBP-3847-UseCategoricalValue

src/main/java/org/generationcp/middleware/dao/dms/DmsProjectDao.java, src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java, src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotsSearchDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionsSearchDto.java, src/main/java/org/generationcp/middleware/pojos/workbench/PermissionsEnum.java, src/test/java/org/generationcp/middleware/service/impl/inventory/PlantingServiceImplIntegrationTest.java
- Make programUUID optional in `DmsProjectDao.GET_CHILDREN_OF_FOLDER`
query: Inventory manager can be program agnostic
- PermissionsEnum: list who can view lots and transactions and use it
in `/studies/tree`
- Lot/Transaction plantingStudyIds filters: add filtering to queries
- PlantingServiceImplIntegrationTest: add additional verifications: 
- `transactionDAO.searchTransactions()`
- `transactionDAO.searchStudyTransactions()`
=> IBP-3806 inventory manager study filter

src/main/resources/liquibase/workbench_changelog/15_4_0.xml, src/main/resources/liquibase/workbench_master.xml
Hi @clarysabel and @nahuel-soldevilla.
In this PR I change the name of the UPDATE_PENDING_TRANSACTIONS permission.
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/369
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/54
Please, review
Regards, Diego
=> IBP-3888 Rename UPDATE_PENDING_TRANSACTIONS permission name

src/main/java/org/generationcp/middleware/domain/gms/GermplasmListNewColumnsInfo.java
- Move columnValuesByListDataIdByName as a method of
GermplasmListNewColumnsInfo
- Use it to display added columns instead of visibleColumnMap (visible
in frontend). This way the added columns are only display after saving
(save as with names and attributes)
=> IBP-3808 Manage Germplasm "Added columns" export	

src/main/java/org/generationcp/middleware/dao/dms/ExperimentPropertyDao.java, src/main/java/org/generationcp/middleware/operation/saver/GeolocationPropertySaver.java, src/test/java/org/generationcp/middleware/dao/dms/ExperimentPropertyDaoTest.java
Remove override process for location if location is not null || eq. to 1
Modified query in getAllFieldMapsInBlockByTrialInstanceId - return fieldmap parent as sitelocationid 
Fix failing unit test
=> IBP-2770-UseFieldParentValueAsFieldMapLocation

src/main/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDao.java, src/test/java/org/generationcp/middleware/dao/dms/ObservationUnitsSearchDaoTest.java
Previously numeric values were cast to unsigned, so values were truncated to integers and some decimal values at the boundaries were incorrectly label as within-bounds.
Cast them using the +0 trick to avoid having to specify a "precision" parameter with other methods (e.g cast to float)
cc @IntegratedBreedingPlatform/developers
=> IBP-3907 Fix "ouf of bound" filter for decimal numbers

src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java, src/main/java/org/generationcp/middleware/pojos/Germplasm.java
This PR is to avoid using the deleted name during the importing germplasm and also fix doesn't show the deleted name in View Germpalsm in Manage Germplasm.
Please, review
=> IBP-3985 germplasm search showing deleted names

src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java, src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotsSearchDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionsSearchDto.java
- Implement harvesting filter 
- Rename "Study of planting" to "Study of use" 
- Restrict "Study of use" to planting transaction type
TODO both UI filters could be combined into one as they are mutually
exclusive.
=> IBP-3978 IBP-3978  IBP-3986 Study of origin (harvesting) filter

src/main/java/org/generationcp/middleware/dao/dms/ExperimentPropertyDao.java, src/main/java/org/generationcp/middleware/operation/saver/GeolocationPropertySaver.java, src/test/java/org/generationcp/middleware/dao/dms/ExperimentPropertyDaoTest.java
This reverts commit 5945ac6d86e7198f79dba4f274ba197d61fb723e (IBP-2770-UseFieldParentValueAsFieldMapLocation), reversing
changes made to 76b634e42aab83c2a36607edb5281afecc4ff8f8.
=> IBP-4036-RevertIBP-2770

src/main/java/org/generationcp/middleware/service/pedigree/string/processors/DoubleCrossProcessor.java, src/main/java/org/generationcp/middleware/service/pedigree/string/processors/SingleCrossHybridProcessor.java, src/main/java/org/generationcp/middleware/service/pedigree/string/processors/ThreeWayHybridProcessor.java, src/test/java/org/generationcp/middleware/service/pedigree/string/processors/DoubleCrossProcessorTest.java, src/test/java/org/generationcp/middleware/service/pedigree/string/processors/SingleCrossHybridProcessorTest.java, src/test/java/org/generationcp/middleware/service/pedigree/string/processors/ThreeWayHybridProcessorTest.java
If null crossing value retain existing value
=> IBP-3977-CrossExpansionExcludeLevelWithNullParent

src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java, src/main/resources/liquibase/crop_changelog/16_4_1.xml, src/main/resources/liquibase/crop_master.xml
It has been detected that germplsm_idx13 affected the performance of
germplasm search filtered count in the uat server.
This index was introduced mainly for the total count, but we saw
omitting this count will greatly improve the overall performance of the
search, and since this count is not of much value for the user, we
remove it altogether.
Middleware
- Remove changeset so that we avoid running the expensive (now
obsolete) index creation for each migration.
- Remove created index wherever the old changeset has run.
BMSAPI / Workbench:
- Remove total count.
Issue: IBP-4241
=> IBP-4241 Remove obsolete index germplsm_idx13, changeset and total count

src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
Fixes performance issue caused by sub-optimal query plan
Clones #979
=> IBP-4320 Force ims_lot_idx01 (eid) in germplasm search

src/main/java/org/generationcp/middleware/api/germplasm/GermplasmService.java, src/main/java/org/generationcp/middleware/api/germplasm/GermplasmServiceImpl.java, src/main/java/org/generationcp/middleware/api/inventory/study/StudyTransactionsDto.java, src/main/java/org/generationcp/middleware/dao/AttributeDAO.java, src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java, src/main/java/org/generationcp/middleware/dao/ims/LotDAO.java, src/main/java/org/generationcp/middleware/dao/ims/TransactionDAO.java, src/main/java/org/generationcp/middleware/domain/germplasm/PedigreeDTO.java, src/main/java/org/generationcp/middleware/domain/germplasm/ProgenyDTO.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/ExtendedLotDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/LotsSearchDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionDto.java, src/main/java/org/generationcp/middleware/domain/inventory/manager/TransactionsSearchDto.java, src/main/java/org/generationcp/middleware/manager/GermplasmDataManagerImpl.java, src/main/java/org/generationcp/middleware/manager/api/GermplasmDataManager.java, src/test/java/org/generationcp/middleware/dao/AttributeDAOTest.java, src/test/java/org/generationcp/middleware/dao/GermplasmDAOTest.java
In dao classes, when selecting germplasmDbId value use germplsm_uuid value 
Rename method to *byGUID 
Adding germplasm_guids property to LotsSeachDTO and TransactionsSearchDTO and use when filtering transactions/seedlots
=> IBP-4349-BrapiUseGermplsmGUID

src/main/resources/liquibase/crop_changelog/17_4_0.xml
Pre condition when creating new cvterm for entry_type, check by id only 
- Use name 'X' if entry_type x doesn't exists, else use 'XRP'
- When creating cvterm_relationship fetched Type of Entry_Type and has value by name, cv_id and is_obsolete
- Special instruction for deleting database change log
=> IBP-4476-EntryTypXChangesetifExists

src/main/resources/liquibase/crop_changelog/17_4_0.xml, src/main/resources/liquibase/workbench_changelog/17_4_0.xml
crop_changelog:
- added changeset 17.4.0-4 : Remove excess space between "Double" and "haploid" in method names [IBP-4238]
- added changeset 17.4.0-5 : Set methods.mprgn to -1 for derivative and maintenance methods [IBP-4533]
workbench_changelog:
- added changeset 17.4.0-4 to set workbench_crop.use_uuid to 0
Please review and merge. 
cc @mcrimi 
[IBP-4238]: https://ibplatform.atlassian.net/browse/IBP-4238
[IBP-4533]: https://ibplatform.atlassian.net/browse/IBP-4533
=> Dm changes v18 : crop changesets 17.4.0-4, 17.4.0-5. workbench changeset 17.4.0-4

src/main/java/org/generationcp/middleware/dao/GermplasmSearchDAO.java
The sub-optimal query is triggered when there are no lots/transactions. I’m not sure what recent change may be causing this because last time it worked without this optimization. It is also likely we are hitting mysql micro-performance issues that are probably solved in recent versions.
=> IBP-4683: fix sub-optimal join between germplsm and transaction

src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationLevelMapper.java, src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationUnitPosition.java, src/main/java/org/generationcp/middleware/api/brapi/v2/observationunit/ObservationUnitServiceImpl.java, src/main/java/org/generationcp/middleware/dao/dms/PhenotypeDao.java, src/main/java/org/generationcp/middleware/enumeration/DatasetTypeEnum.java, src/main/java/org/generationcp/middleware/service/impl/study/PhenotypeQuery.java, src/test/java/org/generationcp/middleware/dao/dms/PhenotypeDaoIntegrationTest.java
- Fix ObservationUnitPosition.observationLevel
- Consolidate mapping and asymmetries in ObservationLevelMapper
Continues in IBP-4289
- Add name to DatasetTypeEnum and use it to map non-canonical
observation levels
=> IBP-4842: Some improvements in brapi v2 observationLevel schema

src/main/java/org/generationcp/middleware/manager/ontology/OntologyVariableDataManagerImpl.java, src/main/java/org/generationcp/middleware/manager/ontology/daoElements/VariableFilter.java
BMSAPI:
- new /variables/filter param: datasetIds
Middleware:
- OntologyVariableDataManagerImpl.getWithFilter is candidate for
refactor but the combination of filters (datasetId+variableTypeIds)
works well for this particular scenario, while other approaches don't
(variableIds+variableTypeIds, supposing we would want pre-gather the
list of variableIds for the dataset)
=> IBP-4917: Associate files only to dataset variables

src/main/java/org/generationcp/middleware/api/file/FileMetadataServiceImpl.java, src/main/java/org/generationcp/middleware/dao/FileMetadataDAO.java, src/main/resources/mw_messages_en.properties
Amends https://github.com/IntegratedBreedingPlatform/Workbench/pull/544
- Move validation from frontend to here
- Same file name is allowed if it belongs to a different path
- We don't add complex locking mechanism, the UI is in charge of locking
while the request is in progress, and other scenarios are
considered edge cases (concurrent request with the same file name and
path)
- No constraints at the table level given that path > 255 bytes
- current length (varchar 2000) is to allow longer file names and also for consistency with URL
- also no constraint might be useful in a future germplasm merge
scenario, where multiple multiple (merged) germplasm have a
corresponding row in file_metadata pointing to the same file path,
which in turns makes possible the merging mechanism without having …
=> IBP-4945: Validate file overwrite

src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListDto.java, src/main/java/org/generationcp/middleware/api/germplasmlist/GermplasmListServiceImpl.java, src/main/java/org/generationcp/middleware/api/germplasmlist/data/GermplasmListDataService.java, src/main/java/org/generationcp/middleware/api/germplasmlist/data/GermplasmListDataServiceImpl.java, src/main/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDataSearchDAO.java, src/main/java/org/generationcp/middleware/pojos/GermplasmList.java, src/main/java/org/generationcp/middleware/pojos/GermplasmListData.java, src/main/resources/liquibase/crop_changelog/19_5_0.xml, src/main/resources/liquibase/crop_master.xml, src/test/java/org/generationcp/middleware/dao/germplasmlist/GermplasmListDataDAOTest.java
- new service method: fill with cross expansion
- Store cross expansion **generationLevel** in `listnms`:
- a property to complement (or potentially migrate in the future) the stored pedigree in listdata.grpname.
- Set it when filling with cross expansion.
- Use it for:
- pre-select generation level dropdown in CROSS column
- "add to list" actions: fill with cross expansion according to list generation level.
=> IBP-5369 fill with cross expansion

src/main/resources/liquibase/workbench_changelog/20_1_0.xml
a clean changeset to leave only the new side menu instead of both.
Script to clean up dbs (mostly dev machines) which had the intermediate changeset applied:
```sql
set @permission_id = (select permission_id from permission where name = 'MANAGE_PROGRAM_SETTINGS_BETA');
delete from role_type_permission where permission_id = @permission_id;
delete from permission where permission_id = @permission_id;
DELETE FROM workbench.workbench_tool WHERE name = 'program_settings_manager';
DELETE FROM workbench.databasechangelog WHERE ID LIKE 'v20.1.0-1' ESCAPE '#' AND AUTHOR LIKE 'nahuel';
DELETE FROM workbench.databasechangelog WHERE ID LIKE 'v20.1.0-2' ESCAPE '#' AND AUTHOR LIKE 'nahuel';
```
=> IBP-4838: Modify final changeset to create new Manage Program settings

src/main/java/org/generationcp/middleware/dao/GermplasmDAO.java
Circumstances changed a bit since the improvement was created (now there is filtering, and both queries use the filtering methods), but idea is the same: make it clear that both count and main queries have this join, and that every new join added to the main query need to be contemplated in the count query.
=> IBP-5447: Reuse PUI base query both in main matches query and in count

src/main/java/org/generationcp/middleware/api/germplasm/pedigree/cop/CopCalculation.java
Original value was copied from python implementation:
https://github.com/IntegratedBreedingPlatform/AWSApps/blob/80756ceae4ccf6d330d8c9a8e9f02dcedeaffa50/COP/ibp_smart-module-lambda-import-master/sm-lambda-import/cop_src/cop/algorithm_v2.py#L147
=> IBP-5621: CopZ for unknown parents should be 0 for btype=0
